services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    name: NextGen-HR
    driver: bridge
