name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch; adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_dir: frontend
            image_tag: hrms-frontend
          - service_dir: backend
            image_tag: hrms-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your personal access token

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service_dir }}  # Use the local directory name
          push: true
          tags: yashsuthar00/${{ matrix.image_tag }}:latest  # Use the Docker Hub repository name
